#!/bin/bash
# spec2cmake.sh — 从 OpenJDK spec.gmk 提取编译参数，生成 CMake 配置
# 用法: bash cmake/spec2cmake.sh [spec.gmk路径] > build/cmake_vars.sh
#       然后: source build/cmake_vars.sh && cmake -B cmake-build $CMAKE_ARGS

set -e

SPEC="${1:-build/*/spec.gmk}"
OUTFILE="${2:-build/cmake_config.cmake}"

if [ ! -f "$SPEC" ]; then
    echo "ERROR: spec.gmk not found at $SPEC. Run 'bash configure ...' first." >&2
    exit 1
fi

BUILD_DIR="$(dirname "$SPEC")"
TOPDIR="$(grep '^TOPDIR' "$SPEC" | head -1 | sed 's/.*:= *//')"

extract() {
    grep "^$1" "$SPEC" | head -1 | sed "s/.*:= *//;s/ *$//"
}

# === 编译器 ===
CC=$(extract 'CC ')
CXX=$(extract 'CXX ')
AR=$(extract 'AR ')
NM=$(extract 'NM ')

# === JDK native 编译标志 ===
CFLAGS_JDKLIB=$(extract 'CFLAGS_JDKLIB')
CXXFLAGS_JDKLIB=$(extract 'CXXFLAGS_JDKLIB')
LDFLAGS_JDKLIB=$(extract 'LDFLAGS_JDKLIB')
CFLAGS_JDKEXE=$(extract 'CFLAGS_JDKEXE')
LDFLAGS_JDKEXE=$(extract 'LDFLAGS_JDKEXE')

# === 额外的编译标志 ===
EXTRA_CFLAGS=$(extract 'EXTRA_CFLAGS')
EXTRA_CXXFLAGS=$(extract 'EXTRA_CXXFLAGS')
EXTRA_LDFLAGS=$(extract 'EXTRA_LDFLAGS')

# === Hotspot 专用 ===
JVM_CFLAGS=$(extract 'JVM_CFLAGS')
JVM_LDFLAGS=$(extract 'JVM_LDFLAGS')
JVM_LIBS=$(extract 'JVM_LIBS')

# === 系统库 ===
LIBZ_LIBS=$(extract 'LIBZ_LIBS')
LIBDL=$(extract 'LIBDL')
LIBM=$(extract 'LIBM')

# === JDK 公共库 ===
JDKLIB_LIBS=$(extract 'JDKLIB_LIBS')

# === 头文件路径 ===
SUPPORT_OUTPUTDIR="$BUILD_DIR/support"
HEADERS_BASE="$SUPPORT_OUTPUTDIR/headers"
MODULES_INCLUDE="$SUPPORT_OUTPUTDIR/modules_include"

# === 链接标志 ===
SHARED_LIBRARY_FLAGS="-shared"

# === 生成 CMake 变量文件 ===
cat > "$OUTFILE" << CMAKEEOF
# Generated by spec2cmake.sh from $SPEC
# Do not edit manually

set(CMAKE_C_COMPILER $CC)
set(CMAKE_CXX_COMPILER $CXX)

# JDK Library Flags
set(JDK_C_FLAGS "${CFLAGS_JDKLIB} ${EXTRA_CFLAGS}")
set(JDK_CXX_FLAGS "${CXXFLAGS_JDKLIB} ${EXTRA_CXXFLAGS}")
set(JDK_LD_FLAGS "${LDFLAGS_JDKLIB} ${EXTRA_LDFLAGS}")
set(JDK_EXE_C_FLAGS "${CFLAGS_JDKEXE} ${EXTRA_CFLAGS}")
set(JDK_EXE_LD_FLAGS "${LDFLAGS_JDKEXE} ${EXTRA_LDFLAGS}")

# Hotspot Flags
set(JVM_CXX_FLAGS "${JVM_CFLAGS}")
set(JVM_LD_FLAGS "${JVM_LDFLAGS}")
set(JVM_LIBS "${JVM_LIBS}")

# System Libraries
set(LIBZ_LIBS "${LIBZ_LIBS}")
set(LIBDL "${LIBDL}")
set(LIBM "${LIBM}")

# JDK Base Libraries (linked by all JDK native libs)
set(JDKLIB_LIBS "${JDKLIB_LIBS}")

# Include Paths
set(JNI_HEADERS_DIR "${HEADERS_BASE}")
set(MODULES_INCLUDE_DIR "${MODULES_INCLUDE}")
set(SUPPORT_OUTPUT_DIR "${SUPPORT_OUTPUTDIR}")

# Build configuration
set(JDK_TOPDIR "${TOPDIR}")
set(JDK_BUILD_DIR "${BUILD_DIR}")
CMAKEEOF

echo "Generated: $OUTFILE"
echo "Use: cmake -B cmake-build -C $OUTFILE $TOPDIR"
